# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "기록의 힘!"
description: > # this means to ignore newlines until "email:"
   난 짱이될거야

email: a-mail@mail.mail
#blog logo
logo: "/assets/images/df_logo.jpg"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: '양승희'
author: '양승희'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "https://seunghee63.github.io/" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@dirkfabisch'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:

  - icon:	github
    url:	https://github.com/seunghee63
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
