name: Deploy

on:
  push:
    branches:
      - master

jobs:
  publish:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: action/checkout@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run build script
        run: |
          npm install
          npm run deploy
