name: Deploy

on:
  push:
    branches:
      - master

jobs:
  publish:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Set git user
        run: |
          git config --global user.email "0603yang@naver.com"
          git config --global user.name "seunghee63" 

      - name: Run build script
        run: |
          npm install
          npm run deploy
